name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Install backend dependencies
        run: npm install --prefix backend

      - name: Build frontend
        run: npm run build:frontend

      - name: Run backend tests
        run: npm --prefix backend test

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/react-vite-deployment-test
            git pull origin main
            echo "Installing frontend dependencies"
            sudo npm install --prefix frontend
            if [ $? -ne 0 ]; then
              echo "Failed to install frontend dependencies"
              exit 1
            fi
            echo "Installing backend dependencies"
            sudo npm install --prefix backend
            if [ $? -ne 0 ]; then
              echo "Failed to install backend dependencies"
              exit 1
            fi
            echo "Building frontend"
            npm run build:frontend
            if [ $? -ne 0 ]; then
              echo "Failed to build frontend"
              exit 1
            fi
            echo "Restarting PM2 processes"
            pm2 restart all
            pm2 logs
