name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies
        run: sudo npm install --prefix frontend

      - name: Install backend dependencies
        run: sudo npm install --prefix backend

      - name: Adjust permissions
        run: |
          sudo chown -R $USER:$USER /var/www/react-vite-deployment-test/frontend/dist
          sudo chmod -R 755 /var/www/react-vite-deployment-test/frontend/dist

      - name: Build frontend
        run: sudo npm run build:frontend

      - name: Run backend tests
        run: sudo npm --prefix backend test

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/react-vite-deployment-test
            git pull origin main
            sudo npm install --prefix frontend
            sudo npm install --prefix backend
            sudo chown -R $USER:$USER /var/www/react-vite-deployment-test/frontend/dist
            sudo chmod -R 755 /var/www/react-vite-deployment-test/frontend/dist
            sudo npm run build:frontend
            if [ $? -ne 0 ]; then
              echo "Failed to build frontend"
              exit 1
            fi
            pm2 restart all
            pm2 logs
