name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Install backend dependencies
        run: npm install --prefix backend

      - name: Build frontend
        run: npm run build:frontend

      - name: Run backend tests
        run: npm --prefix backend test

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/react-vite-deployment-test
            git pull origin main
            sudo npm install --prefix frontend
            sudo npm install --prefix backend
            sudo npm run build:frontend
            pm2 restart all
